### ISSUE TITLE
How to custom animation for scrollview

### ISSUE THREAD

**Issue by longvannguyendx** [setchi/FancyScrollView#12]
Hi,
 I see you posted this in your description : https://github.com/setchi/FancyScrollView/blob/master/Documents/screencast2.gif
But the seem that it's not attached in the examples. Could you please share it? 
BTW, I have a question: You are using the animator (animation) for your scrollview. Could you please help me support step by step to modify animation or something like that to custom animation for scrollview. I tried to custom but it's hard to handle it. 
Thank so much for your scrollview. It's a awesome scrollview.

**Comment by longvannguyendx** [comment]
Hi guy,
 Any update this?
Thanks.

**Comment by setchi** [comment]
Thank you for using FancyScrollView.
Where is hard of custom animation?

**Comment by setchi** [comment]
I will close it once.
Please contact me if there is something again.
