### ISSUE TITLE
Support for Grid Layout

### ISSUE THREAD

**Issue by sorab2142** [setchi/FancyScrollView#14]
Is there a way you could make this support a Grid Layout Group?

**Comment by setchi** [comment]
It is similar things are possible to do so by implementing one cell as a row or column.
But that is troublesome. X(

**Comment by setchi** [comment]
@sorab2142 
Hi, Added Grid Layout demo.

Demo: https://setchi.jp/FancyScrollView/08_GridView
Code: https://github.com/setchi/FancyScrollView/tree/master/Assets/FancyScrollView/Examples/Sources/08_GridView

Thanks.

![anim](https://user-images.githubusercontent.com/8326814/69004520-d2b36b80-0957-11ea-8277-06bfd3e8f033.gif)
