### ISSUE TITLE
Cells are not displayed on iPad when constructed but works fine after touch and slide.

### ISSUE THREAD

**Issue by PhillipZeratul** [setchi/FancyScrollView#15]
Hi, first, great work, thank you ;)\
But I find a bug I think.\
It works fine in the editor but when I built it on my iPad, the cells are not shown on the screen like the picture I attached, it just shows the background. They will show correctly after you touch and slide.\
\
![img_4675](https://user-images.githubusercontent.com/5869965/37131815-4debeb18-22c5-11e8-8bf3-90488d613698.PNG)\
\
How to reproduce:
1. I just cloned this repo and opened it in Unity directly.
2. I'm testing the 02_CellEventHandling scene and built this scene to iPad and run.
3. And the cells are not correctly displayed.

Environment:
Unity 2017.3.1f1
iPad Air 2
iOS 11.1.1

**Comment by setchi** [comment]
@PhilipZeratul 
Thank you for the report.
I do not have an iPad.
Could you please delete this line and try it?
https://github.com/setchi/FancyScrollView/blob/59be9cc1cd6f9ff3694dee808f958d083ff9ab5c/Assets/FancyScrollView/Examples/02_CellEventHandling/Example02ScrollViewCell.cs#L27

**Comment by PhillipZeratul** [comment]
After I deleted this line and rebuild, when the app is started, there is only one cell continually spin from left to right with animation. And it becomes normal after a touch and slide.

**Comment by setchi** [comment]
@PhilipZeratul I will investigate.

**Comment by PhillipZeratul** [comment]
@setchi So, any luck on this?

**Comment by setchi** [comment]
@PhilipZeratul I succeeded in reproducing on my device.
I do not yet understand the cause of the bug.
I will continue the investigation.

**Comment by PhillipZeratul** [comment]
@setchi Hi, I incidentally reproduced similar circumstance in Editor but my project is a little bit complex so I don't know what exactly caused this or how you can reproduce.
There are some things that I noticed though.
1. The Cells are all enabled and Images are all correctly set.
2. They are all at the start position of the animation, as the third picture shows, they all stacked together with transparency.
3. With a touch and slide, the scroll view works correctly.
![screen shot 2018-03-27 at 3 20 13 pm](https://user-images.githubusercontent.com/5869965/37952651-1d96ee14-31d3-11e8-8560-97e06132c3d0.png)

![screen shot 2018-03-27 at 3 20 35 pm](https://user-images.githubusercontent.com/5869965/37952682-2dd3610e-31d3-11e8-903c-bd23a1a81d84.png)

![screen shot 2018-03-27 at 3 20 59 pm](https://user-images.githubusercontent.com/5869965/37952683-2f553138-31d3-11e8-8d9c-4d86362aa9a6.png)

**Comment by PhillipZeratul** [comment]
@setchi Oh, actually it happens when I disable the canvas and re-enable it.
How to reproduce:
1. Open 02_CellEventHandling scene and run.
2. Disable Canvas and re-enable it.
3. The images are all outside the canvas and will show correctly after a touch and slide.

**Comment by setchi** [comment]
@PhilipZeratul Thank you for the report.

Deactivating GameObject resets Animator.
I am in trouble with this behavior.

There is a method to solve by saving the cell position and applying it when OnEnable.
```cs
float currentPosition = 0;

/// <summary>
/// セルの位置を更新します
/// </summary>
/// <param name="position"></param>
public override void UpdatePosition(float position)
{
    currentPosition = position;
    animator.Play(scrollTriggerHash, -1, position);
    animator.speed = 0;
}

void OnEnable()
{
    UpdatePosition(currentPosition);
}
```

Alternatively, you can redraw the cell by calling the FancyScrollView.UpdateContents method.
https://github.com/setchi/FancyScrollView/blob/master/Assets/FancyScrollView/Scripts/FancyScrollView.cs#L145

**Comment by PhillipZeratul** [comment]
@setchi Hi, I find in here, you added `#if UNITY_EDITOR` and if I comment out this macro, the Fancy Scroll View works fine on iPad.
So, what does this LateUpdate() do and why is it not included in builds?
https://github.com/setchi/FancyScrollView/blob/59be9cc1cd6f9ff3694dee808f958d083ff9ab5c/Assets/FancyScrollView/Scripts/FancyScrollView.cs#L81

**Comment by PhilipZeratul** [comment]
@setchi Hi, I find in here, you added `#if UNITY_EDITOR` and if I comment out this macro, the Fancy Scroll View works fine on iPad.
So, what does this LateUpdate() do and why is it not included in builds?
https://github.com/setchi/FancyScrollView/blob/59be9cc1cd6f9ff3694dee808f958d083ff9ab5c/Assets/FancyScrollView/Scripts/FancyScrollView.cs#L81

**Comment by setchi** [comment]
@PhilipZeratul I appreciate it.

It is for reflecting these values in real time when changing these values on the inspector.

In devices, these values are immutable, so they were reflected only by the editor.

However, checking every frame is not a big cost, so you can delete this macro without problems.

**Comment by PhillipZeratul** [comment]
@setchi Thank you for the support!
I changed the OnEnable and LateUpdate part of the code, the performance cost is subtle so I think the Fancy Scroll View works perfectly fine now! Keep up the good work and be Fancier ;)
