### ISSUE TITLE
How to stop scroll if the first or the last item.

### ISSUE THREAD

**Issue by longvannguyendx** [setchi/FancyScrollView#21]
I want to stop scroll if the first item on top or the last item on bottom?

**Comment by setchi** [comment]
@longvannguyendx 
Currently not supported. It is possible if you customize Scroller.
I will consider implementation in the future.
Thank you.

**Comment by longvannguyendx** [comment]
Hi,
 Thanks for your answer. I hope you have free time to implement this feature.
Thanks,

**Comment by zyowo** [comment]
I need this too. Just like the traditional scrollview calculation, the drag range should be the first child at the top of the scrollview and the last child at the bottom of the scrollview.

**Comment by zyowo** [comment]
But this design violates the way `Snap` is written. You can't scroll to the last few children by dragging.

**Comment by setchi** [comment]
@longvannguyendx @zyowo 
I'm making a prototype now. It uses `ScrollRect` instead of `Scroller`.
It will probably released by November 5th.

**Comment by longvannguyendx** [comment]
@setchi 
Thank you so much for your time to implement this.
Thank again for your Fancy scrollview.  :*

**Comment by setchi** [comment]
@longvannguyendx @zyowo
WIP: https://setchi.jp/FancyScrollView/Example07/

**Comment by longvannguyendx** [comment]
> @longvannguyendx @zyowo
> WIP: https://setchi.jp/FancyScrollView/Example07/

Hi guy,
 I have just tested this feature and I see a minor bug.  Cell is not destroy when you stop running app.
 If you have free time, you should include the scroll page feature. I only feedback to you for improving your scrollview . I hope my feedback don't make you feel uncomfortable. :)

![Capture1](https://user-images.githubusercontent.com/10340624/68108181-b2c48680-ff19-11e9-884e-676047ad7263.PNG)


Thanks.

**Comment by setchi** [comment]
@longvannguyendx 
Thank you for your feedback!
I fixed that bug x(
https://github.com/setchi/FancyScrollView/commit/6db1a4ddc5aca48d7e96f3d1f6709dc0b730dfd6

Is `scroll page feature` something like `Scroller.ScrollTo()` ?

**Comment by setchi** [comment]
In the future, `ScrollTo(int index, float duration, Ease easing)` will be implemented in [FancyScrollRect](https://github.com/setchi/FancyScrollView/blob/master/Assets/FancyScrollView/Sources/Runtime/FancyScrollRect.cs).

**Comment by longvannguyendx** [comment]
Hi,
  For example:  we have 3 cells in one page, and we will snap page by page. 
  Please see image attachment.
![1](https://user-images.githubusercontent.com/10340624/68109889-47c97e80-ff1e-11e9-9693-07dc50e3047d.png)

Thanks.

**Comment by setchi** [comment]
@longvannguyendx 
Try like this. This is an example.
```cs
public class CellData
{
    public int Message; // Cell Data
}

public class PageData
{
    public CellData Cell1;
    public CellData Cell2;
    public CellData Cell3;
}

public class ScrollView : FancyScrollView<PageData>
{
...
}

public class Page : FancyScrollViewCell<PageData>
{
    public override void UpdateContent(PageData pageData)
    {
        // show page data
    }
}
```

**Comment by setchi** [comment]
@longvannguyendx @zyowo 
Added uGUI ScrollRect-like demo. Close this issue.
https://github.com/setchi/FancyScrollView/tree/master/Assets/FancyScrollView/Examples/Sources/07_ScrollRect

![07_ScrollRect](https://user-images.githubusercontent.com/8326814/68384224-84a1a980-019a-11ea-9cee-aa6acc4860e2.gif "07_ScrollRect")

**Comment by zyowo** [comment]
Wow! This new feature saved my project. thank you very much!
Sorry, I didn't see it in time.

**Comment by zyowo** [comment]
I want to share the status of using `ScrollRect` in my project. 
In fact, children who cannot be moved to the _Scroll Offset_ are fake and they don't need to be `ScrollTo`. Only the parts that can be moved to the _Scroll Offset_  need to be `ScrollTo`.

![image](https://user-images.githubusercontent.com/30146416/68443190-2e6e4e00-020e-11ea-941b-e4a69fa934f9.png)

**Comment by zyowo** [comment]
Emm, it seems that there is no problem. If each Cell can be ScrollTo, I could make a special judgment on the fake cell.
