### ISSUE TITLE
Can you add scroll with page?

### ISSUE THREAD

**Issue by longvannguyendx** [setchi/FancyScrollView#22]
Hi,
  Can you add the feature scroll for each page.?
Thanks.

**Comment by setchi** [comment]
@longvannguyendx 
It is possible to have different animation for each page based on Index + position value, not just position value.

Index: 
https://github.com/setchi/FancyScrollView/blob/master/Assets/FancyScrollView/Sources/Runtime/FancyScrollViewCell.cs#L11

**Comment by longvannguyendx** [comment]
Hi,
 Could you please implement this in your FancyScrollView?
I hope you will spend time to implement this.
Thank you so much and have a nice day. :)
Thanks.
