### ISSUE TITLE
My ScrollView cannot drag.

### ISSUE THREAD

**Issue by JourneyHans** [setchi/FancyScrollView#23]
My ScrollView is full screen, and the Cell is just Text Prefab, I don't add any animation.

**Comment by JourneyHans** [comment]
So...I have to add animation to Cell even if I just want a simple move action, is that right?

**Comment by setchi** [comment]
@JourneyHans 
Yes, cell movement is based solely on the [UpdatePosition](https://github.com/setchi/FancyScrollView/blob/master/Assets/FancyScrollView/Examples/Sources/01_Basic/Cell.cs#L21-L26) implementation.

The sample uses Animator, but it is possible to implement it like him without using Animator.
https://gitlab.com/syousuke1104/unity_customfancyscrollview/blob/8edb0b31129a2c08fd791569a827ef2cf68d6b7b/Assets/CustomFancyScrollView/Scripts/CustomCell.cs#L36-51

**Comment by JourneyHans** [comment]
Thank you very much. It solved my problem, your implementation of "ScrollView" is the most elegant way I have ever saw.
