### ISSUE TITLE
Different Cell Size support

### ISSUE THREAD

**Issue by songtm** [setchi/FancyScrollView#24]
Hi, first thanks for this amazing plugin.
I was struggling to expand this plugin to support  cells with different height.  
![differentCellHeight](https://user-images.githubusercontent.com/8175056/64167944-0f091c80-ce7d-11e9-8d0b-aded1c491d35.png)

I find it is hard to do. Do you have any idea how to achieve that?  Thanks

**Comment by setchi** [comment]
@songtm
It is currently not supported, so the best solution is to use UGUI Super Scroll View.
https://assetstore.unity.com/packages/tools/gui/ugui-super-scrollview-86572

Thanks.

**Comment by songtm** [comment]
thanks for your advice, I'll check out that
