### ISSUE TITLE
Is it possible to give images instead of white and blue color

### ISSUE THREAD

**Issue by ranjithAmeen** [setchi/FancyScrollView#25]
Hi Sir,
Is it possible to assign images to those white and blue cells. I tried to change them to image but i failed to get results.
please help me
thank you

**Comment by setchi** [comment]
@ranjithAmeen 
04_Metaball? Others?

**Comment by ranjithAmeen** [comment]
Not metaball . Other one with rectangle shape. Thank you for reply sir.

**Comment by setchi** [comment]
@ranjithAmeen 
Try like this. This is an example.
```cs
public class ItemData
{
    public string ImagePath { get; }
    public ItemData(string imagePath) => ImagePath  = imagePath;
}
```
```cs
public class Cell : FancyScrollViewCell<ItemData>
{
    ...
    [SerializeField] RawImage rawImage;
    ...

    public override void UpdateContent(ItemData itemData)
    {
        Texture2D texture = null; // Load a texture using itemData.ImagePath

        rawImage.texture = texture;
    }
    ...
}
```

**Comment by ranjithAmeen** [comment]
Hi,
Thank you for help. 
After your suggestion i have changed code like this

public class Cell : FancyScrollViewCell<ItemData, Context>
    {
        [SerializeField] Animator animator = default;
        [SerializeField] Text message = default;
        [SerializeField] Image image = default;
        [SerializeField] Button button = default;
        [SerializeField] RawImage rawImage;//**
.
.
.
public override void UpdateContent(ItemData itemData)
        {
         string filePath = "\\texture\\2.png";
            Texture2D texture = null;
            byte[] fileData;

            if (File.Exists(filePath))
            {
                fileData = File.ReadAllBytes(filePath);
                texture = new Texture2D(2, 2);
                texture.LoadImage(fileData);
            }
           
            rawImage.texture = texture;
      }

namespace FancyScrollView.Example02
{
    public class ItemData
    {
        public string ImagePath { get; }//**
        public ItemData(string imagePath) => ImagePath = imagePath;//**
    }
}

But sir its giving some null reference exception i am not able resolve it. error is like this 
"NullReferenceException: Object reference not set to an instance of an object
FancyScrollView.Example02.Cell.UpdateContent (FancyScrollView.Example02.ItemData itemData) (at Assets/FancyScrollView/Examples/Sources/02_FocusOn/Cell.cs:49)
FancyScrollView.FancyScrollView`2[TItemData,TContext].UpdateCells (System.Single firstPosition, System.Int32 firstIndex, System.Boolean forceRefresh) (at Assets/FancyScrollView/Sources/Runtime/FancyScrollView.cs:112)
FancyScrollView.FancyScrollView`2[TItemData,TContext].UpdatePosition (System.Single position, System.Boolean forceRefresh) (at Assets/FancyScrollView/Sources/Runtime/FancyScrollView.cs:57)
FancyScrollView.FancyScrollView`2[TItemData,TContext].Refresh () (at Assets/FancyScrollView/Sources/Runtime/FancyScrollView.cs:36)
FancyScrollView.FancyScrollView`2[TItemData,TContext].UpdateContents (System.Collections.Generic.IList`1[T] itemsSource) (at Assets/FancyScrollView/Sources/Runtime/FancyScrollView.cs:30)
FancyScrollView.Example02.ScrollView.UpdateData (System.Collections.Generic.IList`1[T] items) (at Assets/FancyScrollView/Examples/Sources/02_FocusOn/ScrollView.cs:43)
FancyScrollView.Example02.Example02.Start () (at Assets/FancyScrollView/Examples/Sources/02_FocusOn/Example02.cs:31)
"
I am also trying to assign different images to different rectangle. Please help me resolve it.
Thank you very much for your time sir
Ranjith

**Comment by ranjithAmeen** [comment]
Hi,
I think i am making mistake here
`namespace FancyScrollView.Example02
{
    public class Example02 : MonoBehaviour
    {
        [SerializeField] ScrollView scrollView = default;
        [SerializeField] Button prevCellButton = default;
        [SerializeField] Button nextCellButton = default;
        [SerializeField] Text selectedItemInfo = default;

        void Start()
        {
            prevCellButton.onClick.AddListener(scrollView.SelectPrevCell);
            nextCellButton.onClick.AddListener(scrollView.SelectNextCell);
            scrollView.OnSelectionChanged(OnSelectionChanged);

            //var items = Enumerable.Range(0, 20)
            //    .Select(i => new ItemData($"Cell {i}"))
            //    .ToArray();

            var items = Enumerable.Range(0, 20)
                .Select(i => new ItemData($"\\texture\\2.png"))
                .ToArray();
            // is above line is correct
            scrollView.UpdateData(items);
            scrollView.SelectCell(0);
        }

        void OnSelectionChanged(int index)
        {
            selectedItemInfo.text = $"Selected item info: index {index}";
        }
    }
}
`

**Comment by setchi** [comment]
@ranjithAmeen 
Hi, Added load texture demo.
Thanks.

Demo: https://setchi.jp/FancyScrollView/09_LoadTexture
Code: https://github.com/setchi/FancyScrollView/tree/master/Assets/FancyScrollView/Examples/Sources/09_LoadTexture

![anim](https://user-images.githubusercontent.com/8326814/70638335-0b571400-1c7c-11ea-8701-a0d1ae0cb7e3.gif)
