### ISSUE TITLE
How to add own object instead of instantiating cell?

### ISSUE THREAD

**Issue by RamaBurni** [setchi/FancyScrollView#26]
I wanted to add my own button from scrollrect.
I create arry to contain those object.
try to use that arry instead of cell but get confused with too many changes.
in the end, can't use the script for buttons.
can anyone help me with this?
I want to use fancy scroll view in my project. for scrollrect.

**Comment by setchi** [comment]
@RamaBurni 
I don't understand the situation.
Is it possible to explain with images?

**Comment by RamaBurni** [comment]
Sorry, I discard that changes due to not working and many errors.
but I can explain the situation.
I want to apply a scroll view script to my scroll view.
I already have buttons include scroll view. and in fancy scroll view, you use cell prefab which instantiates.
I create an array of game object and add my buttons in that. use that arry object instead of cell object.
but after many changes, it was not working.b i don't know where i make mistake, i was in rush and work was on deadline so i did not do more research in it.

**Comment by setchi** [comment]
@RamaBurni 
If possible, share a project that reproduces the bug.
If there is a bug in FancyScrollView I will fix it.

**Comment by RamaBurni** [comment]
No, I'm not saying there is a bug. 
I was saying it is hard to implement in the project. I am not that pro level.
if possible please provide an example scene with actual buttons instead of using cell by instantiating.
sorry for the misleading query.
I forget to mention it.

**Comment by setchi** [comment]
@RamaBurni 
FancyScrollView is data driven.
Display everything based on the passed `List<ItemData>` and `Cell.UpdateContents` method implementation.
If you do something exceptional, you can use `Context`. [Example_02](https://github.com/setchi/FancyScrollView/tree/master/Assets/FancyScrollView/Examples/Sources/02_FocusOn) or later.

Thanks.

**Comment by RamaBurni** [comment]
I will try it.
Thank you.
