### ISSUE TITLE
scroll cells different spacing between each other

### ISSUE THREAD

**Issue by mcaisw** [setchi/FancyScrollView#27]
I want show my scroll view in a container,but the container isn't full screen,and then scroll cells has different spaces between each other.
<img width="379" alt="屏幕快照 2019-09-20 下午11 16 52" src="https://user-images.githubusercontent.com/21421885/65339291-6be72f80-dbfe-11e9-8b65-5b9578d2dd8b.png">

**Comment by setchi** [comment]
@mcaisw 
Please check Animation Curves.
I think you need to linear the animation curve.

Curved:
<img width="561" alt="Screen Shot 2019-09-21 at 1 14 00" src="https://user-images.githubusercontent.com/8326814/65342234-4a417480-dc0d-11e9-897b-efa691094100.png">

Linear:
<img width="576" alt="Screen Shot 2019-09-21 at 1 14 17" src="https://user-images.githubusercontent.com/8326814/65342236-4ca3ce80-dc0d-11e9-8537-49a5ca4fda78.png">

**Comment by mcaisw** [comment]
@setchi Thank you for your reply, I will try it later.

**Comment by mcaisw** [comment]
> @mcaisw
> Please check Animation Curves.
> I think you need to linear the animation curve.
> 
> Curved:
> <img alt="Screen Shot 2019-09-21 at 1 14 00" width="561" src="https://user-images.githubusercontent.com/8326814/65342234-4a417480-dc0d-11e9-897b-efa691094100.png">
> 
> Linear:
> <img alt="Screen Shot 2019-09-21 at 1 14 17" width="576" src="https://user-images.githubusercontent.com/8326814/65342236-4ca3ce80-dc0d-11e9-8537-49a5ca4fda78.png">

Awesome! it's works,Thanks!!!

**Comment by mcaisw** [comment]
My cell default animation isn't linear.
