### ISSUE TITLE
GameObjectのInactive後のActiveでセルが描画されない

### ISSUE THREAD

**Issue by akerusoft** [setchi/FancyScrollView#3]
サンプルの01_Basicを動かして下記の画像のように途中までスクロールした状態でシーン内のScrollViewのGameObjectの状態をInactiveからActiveに変えるとセルの状態が描画されないことがあります。

![image](https://user-images.githubusercontent.com/17823420/28505556-0b8de57c-7060-11e7-820c-4be15dda45c0.png)

このような状態を回避するためには、どのようにすればよいでしょうか？

**Comment by setchi** [comment]
ありがとうございます。

対処法は、GameObjectをActive状態にした際に、ScrollView側のUpdateContentsメソッドを呼び出すことでセルを再描画できます。
https://github.com/setchi/FancyScrollView/blob/master/Assets/FancyScrollView/Scripts/FancyScrollView.cs#L146

GameObjectをDeactive状態にするとAnimatorがリセットされるのは、現状のUnityの仕様のようです。
サンプルではセルをAnimatorでスクロールさせており、Animatorがリセットされるとセルが描画されなくなります。
http://tsubakit1.hateblo.jp/entry/2015/02/05/111819

**Comment by akerusoft** [comment]
さっそくの返答ありがとうございます。
リンクの内容をみてCellのMonoBehaviour.OnEnable(), OnDisable()でAnimatorのnormalizedTimeを取得して復元する処理で問題を回避できました。
