### ISSUE TITLE
how to implement n columns m row scroll view

### ISSUE THREAD

**Issue by mcaisw** [setchi/FancyScrollView#31]
Is it possible to creat a n columns m row scroll view

**Comment by setchi** [comment]
@mcaisw 
Not officially supported.
But it can be implemented as follows.

```cs
public class Entity
{
    public string Message; // Entity Data
    public Entity(string message) => Message = message;
}

public class Row
{
    public Entity[] Entities;
    public Row(Entity[] entities) => Entities = entities;
}

public class ScrollView : FancyScrollView<Row>
{
    void Start()
    {
        const int DataCount = 20;
        const int ColumnCount = 3;

        var rows = Enumerable.Range(0, DataCount)
            .GroupBy(i => i / ColumnCount)
            .Select(group => group
                .Select(i => new Entity($"Entity {i}")).ToArray())
            .Select(entities => new Row(entities))
            .ToArray();

        base.UpdateContents(rows);
    }
}

public class RowCell : FancyScrollViewCell<Row>
{
    public override void UpdateContent(Row row)
    {
        // Show row.Entities[] data
    }
}
```

**Comment by mcaisw** [comment]
![image](https://user-images.githubusercontent.com/21421885/68454702-6ab4a500-0234-11ea-9363-76e8326c98ea.png)
Hope adding this feature to subsequent updates. @setchi

**Comment by setchi** [comment]
@mcaisw 
Hi, Added Grid Layout demo.

Demo: https://setchi.jp/FancyScrollView/08_GridView
Code: https://github.com/setchi/FancyScrollView/tree/master/Assets/FancyScrollView/Examples/Sources/08_GridView

![anim](https://user-images.githubusercontent.com/8326814/69004520-d2b36b80-0957-11ea-8277-06bfd3e8f033.gif)

Thanks.
