### ISSUE TITLE
Unity reports a Shader warning on the Veroni example

### ISSUE THREAD

**Issue by SimonDarksideJ** [setchi/FancyScrollView#33]
The following warning is reported by Unity on the Shader used in the Veroni example

As follows

```
Shader warning in 'FancyScrollViewGallery/Voronoi': 'i': loop control variable conflicts with a previous declaration in the outer scope; most recent declaration will be used at Assets/unity-ui-extensions/Examples/FancyScrollView/Sources/05_Voronoi/Voronoi.hlsl(66) (on d3d11)

Compiling Vertex program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_COLORSPACE_GAMMA UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR
```

It seems to dislike the Index "i" being used in both unroll loops.

Simple fix for the second unroll seems to be to change it to another name, e.g. "j"

**Comment by setchi** [comment]
@SimonDarksideJ 
Thank you for the report!

Fixed : https://github.com/setchi/FancyScrollView/commit/1852f5042231b777654dfd9309ece3e8f2fcca5b

I didn't notice because the warnings doesn't report on macOS.
On Windows, the warnings was reported.

**Comment by SimonDarksideJ** [comment]
Same fix I applied locally which works, thanks
