### ISSUE TITLE
要素が重なるように配置するとオーダーが崩れる

### ISSUE THREAD

**Issue by honda-tatsuya** [setchi/FancyScrollView#36]
uGUIで使っております。
要素が重なるように配置すると、オブジェクトの使い回しをする箇所でオーダーが崩れます。
ヒエラルキー上の順番をID順に揃える方法はありませんでしょうか？

**Comment by setchi** [comment]
@honda-tatsuya 
表示順は UI によって手前に表示したいアイテムが異なるのでライブラリ側では現在のところあえて触れていません。

セルの [UpdateContent](https://github.com/setchi/FancyScrollView/blob/master/Assets/FancyScrollView/Sources/Runtime/Core/FancyScrollViewCell.cs#L52) メソッド内で [Index](https://github.com/setchi/FancyScrollView/blob/master/Assets/FancyScrollView/Sources/Runtime/Core/FancyScrollViewCell.cs#L23) の値を使って下記のような実装をすると期待した挙動が実現できます。
やや強引な実装なのですが [UpdateContent](https://github.com/setchi/FancyScrollView/blob/master/Assets/FancyScrollView/Sources/Runtime/Core/FancyScrollViewCell.cs#L52) は [UpdatePosition](https://github.com/setchi/FancyScrollView/blob/master/Assets/FancyScrollView/Sources/Runtime/Core/FancyScrollViewCell.cs#L58) に比べて呼ばれる頻度は少なくパフォーマンスのボトルネックになることは少ないと思われます。

```cs
public override void UpdateContent(ItemData itemData)
{
    var isFirst = Index <= transform.parent.Cast<Transform>().Min(x => x.GetComponent<Cell>().Index);
    if (isFirst)
    {
        transform.SetAsFirstSibling();
    }
    
    var isLast = Index >= transform.parent.Cast<Transform>().Max(x => x.GetComponent<Cell>().Index);
    if (isLast)
    {
        transform.SetAsLastSibling();
    }
}
```

**Comment by honda-tatsuya** [comment]
ループさせない場合はいただいたコードで期待した動作が得られました。
ループさせる場合は、より強引ですが以下でどうにかなりました。
ご回答ありがとうございます。

```csharp
private float _position;

public override void UpdateContent(ItemData itemData)
{
    foreach (var x in transform.parent.Cast<Transform>().OrderBy(x => x.GetComponent<Cell>()._position))
    {
        x.transform.SetAsLastSibling();
    }
}

public override void UpdatePosition(float position)
{
    _position = position;
}
```
