### ISSUE TITLE
RFC: port package.json, license file back to master branch

### ISSUE THREAD

**Issue by favoyang** [setchi/FancyScrollView#41]
Hi @setchi,

Thanks for creating the awesome upm package. I noticed that you [contribute the package](https://github.com/openupm/openupm/pull/9) to OpenUPM list, but it's [fail on the build pipeline](https://beta.openupm.com/packages/jp.setchi.fancyscrollview/).

The reason is that the build pipelines will checkout each valid semver git tags, and build package from there. For this project, only the upm branch contains the package.json and other necessary upm files (licenses...). As a result, the package can be only installed via git url.

Here's the suggestion to fix the issue with better folder strucutre (also make it more consistent between different branches).

1. port package.json and other necessary files back to master `Assets/FancyScrollView/`
1. consider to move the `Assets/FancyScrollView/` to `Packages/jp.setchi.fancyscrollview` to it a local package. So you always test your library as a package in the unity project.
1. optional you can move Example folder to `Samples~` and update the package.json. see https://forum.unity.com/threads/samples-in-packages-manual-setup.623080/, it will be shown in the package manager ui window.

Here's the steps for further releases

1. bump version in package.json and commit.
2. git subtree Packages/jp.setchi.fancyscrollview to the upm branch.
3. push changes.
3. go to github releases page, create new release (tag) from upm branch and name as vx.y.z to match the version number from package.json.

(openupm will detect the changes, and publish new version).

Hope this help.

**Comment by favoyang** [comment]
Here's an example repo - https://github.com/mob-sakai/UpmGitExtension/tree/master

The master branch [Packages/com.coffee.upm-git-extension](https://github.com/mob-sakai/UpmGitExtension/tree/master/Packages/com.coffee.upm-git-extension) is the main package folder, however all the releases i.e. [v1.0.1](https://github.com/mob-sakai/UpmGitExtension/tree/v1.0.1) are based on [upm branch](https://github.com/mob-sakai/UpmGitExtension/tree/upm).

**Comment by setchi** [comment]
@favoyang 
Thanks for your advice!
The build pipeline job was succeeded.
Later I will try to configure it using the git subtree.

<img width="486" alt="Screen Shot 2019-12-20 at 22 22 03" src="https://user-images.githubusercontent.com/8326814/71257857-1e529e00-2378-11ea-9dbc-3e07c1538e7e.png">

**Comment by favoyang** [comment]
Looks great. I have documented the related information in docs - https://beta.openupm.com/docs/adding-upm-package.html#handling-different-folder-structures
