### ISSUE TITLE
Dublicate snap settings in Scroller inspector

### ISSUE THREAD

**Issue by NyanCetch** [setchi/FancyScrollView#46]
The latest versions of Unity with a new interface have added incorrect display of snap settings. This was not seen on versions prior to 2019.3. Settings are duplicated. It is fixed by commenting or deleting a section of the code from screenshot 3 in ScrollerEditor.cs.

![Before](https://user-images.githubusercontent.com/20258425/89711710-32561900-d9b6-11ea-875a-c8b509691034.png)
![After](https://user-images.githubusercontent.com/20258425/89711723-4ac63380-d9b6-11ea-9463-0a6b5a4270b9.png)

![Reason](https://user-images.githubusercontent.com/20258425/89711775-84973a00-d9b6-11ea-806d-33c6daddcf46.png)

**Comment by setchi** [comment]
@NyanCetch Thank you for the report!
Fixed it https://github.com/setchi/FancyScrollView/commit/9bf1fd8148e82dba953d5b51d252d3d8db0936f8
