### ISSUE TITLE
Please add assembly definition

### ISSUE THREAD

**Issue by derwaldgeist** [setchi/FancyScrollView#53]
We're referencing FancyScrollView from Unity's package manager instead of importing it into the Assets folder (i.e. the new recommended way).

Now we want to add Unit Tests to our project, which requires us to setup assembly definitions for our code. Which in turn requires us to reference any third party library in our .asmdef file.

However, this is only possible if the library itself contains an .asmdef file. We can add these for libraries in the Assets folder, but not for libraries in the package manager.

So I wanted to kindly ask you to provide an .asmdef file as part of the default library. Thanks.

**Comment by obx100** [comment]
Does FancyScrollView.asmdef is you need?

**Comment by derwaldgeist** [comment]
Never mind. Found it :-) Sorry for bothering and thanks for the super-fast response.
