### ISSUE TITLE
Is there a way to support snap funciton for FancyScrollRect component？

### ISSUE THREAD

**Issue by FlowSand** [setchi/FancyScrollView#54]
As the title, tried to modify the source code  by myself but seem to be incorrect. I want to ask a way to support snap for ScrollRect component，or the author did not add this feature because it's necessary？

**Comment by setchi** [comment]
@FlowSand 
ScrollRect does not support snap, because ScrollRect cannot snap to the top cell or the bottom cell.
Consider using `FancyScrollView<ItemData, Context>`. 

Example: https://github.com/setchi/FancyScrollView/tree/master/Assets/FancyScrollView/Examples/Sources/03_InfiniteScroll

**Comment by FlowSand** [comment]
@setchi 
Thanks！I should have misunderstood the snap function and ScrollRect. Example03 did solve my problem！
