### ISSUE TITLE
Instantiate cell object from prefab

### ISSUE THREAD

**Issue by rfadeev** [setchi/FancyScrollView#8]
Is there any special reason for instantiating cells from `cellBase`  which is set to inactive in `FancyScrollView`'s `Awake`? I was thinking that support of instantiating from prefab can be useful, plus it would allow not having disabled `cellBase` object in heirarchy.

**Comment by setchi** [comment]
Thank you.

Certainly, I think it is convenient to instantiate from prefab.
I tried it, there seems to be no problem. I updated samples. https://github.com/setchi/FancyScrollView/commit/32d41954b90e7ff210fe9f95d6508d63e6fc8ae5
Please tell me if you have any comments.

**Comment by rfadeev** [comment]
@setchi Great, thanks! Actually I was thinking to implement this, but was afraid of too drastic API change since FancyScrollView users need to extract their objects from heirarchies to prefabs, otherwise they would have enabled instance of "original" cell base. For example Unity UI Extensions project could be affected if they would like to update their FancyScrollView code to this version.

One comment: prefabs for examples 1 and 2 are disabled, while for examples 3 and 4 are enabled. Is it intended?

**Comment by setchi** [comment]
I did not intend. Fixed! https://github.com/setchi/FancyScrollView/commit/8ed0641d9a81d76ef4330f66eda8d16dde47f1fa
Thanks.
